"""The hardcoded license exceptions

`curl
https://raw.githubusercontent.com/spdx/license-list-data/master/json/exceptions.json
| jq .exceptions[].licenseExceptionId`
"""

LICENSE_EXCEPTION_LIST = [
    "gnu-javamail-exception",
    "LLVM-exception",
    "Fawkes-Runtime-exception",
    "Libtool-exception",
    "Autoconf-exception-3.0",
    "OCCT-exception-1.0",
    "389-exception",
    "SHL-2.1",
    "Nokia-Qt-exception-1.1",
    "Font-exception-2.0",
    "LGPL-3.0-linking-exception",
    "Bison-exception-2.2",
    "i2p-gpl-java-exception",
    "u-boot-exception-2.0",
    "FLTK-exception",
    "GPL-CC-1.0",
    "Classpath-exception-2.0",
    "Bootloader-exception",
    "Linux-syscall-note",
    "SHL-2.0",
    "Qt-GPL-exception-1.0",
    "mif-exception",
    "Swift-exception",
    "WxWindows-exception-3.1",
    "GStreamer-exception-2008",
    "CLISP-exception-2.0",
    "GStreamer-exception-2005",
    "Universal-FOSS-exception-1.0",
    "GCC-exception-2.0",
    "freertos-exception-2.0",
    "OpenJDK-assembly-exception-1.0",
    "GPL-3.0-linking-source-exception",
    "OCaml-LGPL-linking-exception",
    "Autoconf-exception-2.0",
    "Qwt-exception-1.0",
    "openvpn-openssl-exception",
    "GPL-3.0-linking-exception",
    "DigiRule-FOSS-exception",
    "eCos-exception-2.0",
    "Qt-LGPL-exception-1.1",
    "PS-or-PDF-font-exception-20170817",
    "LZMA-exception",
    "KiCad-libraries-exception",
    "GCC-exception-3.1",
]
